---
# tasks file for nfs-client

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Import install tasks
  import_tasks: install.yml
  tags: ['nfs-client', 'nfs-client-install']

- name: Import configuration tasks
  import_tasks: configure.yml
  tags: ['nfs-client', 'nfs-client-configure']

- name: Import service tasks
  import_tasks: service.yml
  tags: ['nfs-client', 'nfs-client-service']

- name: Optionally include monitoring tasks
  include_tasks: 'monitoring/{{ nfs_client__monitoring }}.yml'
  when: nfs_client__monitoring is defined
  tags: ['nfs-client', 'nfs-client-monitoring']
