---

- name: Ensure NFS services are started and enabled on boot
  service:
    name: '{{ item }}'
    enabled: '{{ nfs_client__service_enabled|bool }}'
    state: "{{ nfs_client__service_enabled|bool|ternary('started', 'stopped') }}"
  with_items: '{{ nfs_client__service_names|list }}'
